### ISSUE TITLE
gvle : new option to automatically connect I/O ports having the same name

### ISSUE THREAD

**Issue by eric-casellas** [vle-forge/vle#111]
It would be practical to have a new option that automatically connects all input and output ports having the same name (within a single level of coupled model)

**Comment by rtrepos** [comment]
Good idea.; Should be feasible in the new gvle fot three contextual right click menus in the Diagram:
- when a model port is selected: all connection to/from this port
- when a embedded model (into the current coupled model ): all connections to/from the embedded model ports
- when the coupled model is selected: all connections to/from all ports of all embedded models

**Comment by quesnel** [comment]
Closing now. Feel free to submit a PR. Thanks.
