### ISSUE TITLE
Build fails in gui

### ISSUE THREAD

**Issue by pierreblavy2** [vle-forge/vle#147]
PROBLEM : 
- Sometimes the clean/configure/build menu is displayed in grey (i.e. not available) while no command are running
- Sometimes a build a clean and a configure command can be launched at the same time.
- Sometimes the build or the configure starts, but stops before it finishes. After such stop, the menu allows to launch new commands, but nothing is done when I ask for them

--> Building/configuring/cleaning using the command line with vle in a terminal works.

WORKAROUND
run in a terminal : vle -P xxx clean configure build;

OTHER INFO:
I think something is bugged in the link between the GUI and the command line because compiling with vle works.

The object that send command lines must be unique. It has the responsibility to  launch only one command line at a time (even in a multi thread context). It must  warn the GUI (or any observator) when the terminal status (running something v.s. not running something) changes .

**Comment by quesnel** [comment]
See VLE 2.
