### ISSUE TITLE
A proposal for observation of Executive  

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#151]
Executive has no default observation method.
Since vle-1.1 values can be defined as user values with id.
I suggest one could add a default behavior of observation in a new output plugin.
The Executive::observation method sends on port e.g. "Vpz" a new UserValue that contains a pointer to a Vpz. The observation then writes the vpz into a file that ideally could be simulated.

**Comment by quesnel** [comment]
Closing now. Feel free to submit a PR. Thanks.
