### ISSUE TITLE
DTD validation Request

### ISSUE THREAD

**Issue by Quentin-B** [vle-forge/vle#161]
The  xml file that is saved from the VLE is not validating with the given DTD, the following errors are showing, 

empty.vpz:72: element views: validity error : Element views content does not follow the DTD, expecting (outputs , observables , view*), got ()
</views>
        ^
Failed to validate empty.vpz
The DTD might need to be updated to fix the issue.

**Comment by quesnel** [comment]
Seems to be fix. Closing now. Feel free to reopen if you still see some warnings.
