### ISSUE TITLE
gvle - Forrester Plugin

### ISSUE THREAD

**Issue by duboz** [vle-forge/vle#178]
When using the Forester plugin, it seems to be impossible to re-open the plugin with an existing defined dynamics (previously created with the plugin). It is important to be able to re-open the dynamic by using the plugin for obvious maintenance and evolution reasons.

**Comment by rtrepos** [comment]
In the newer version of gvle (based on Qt) the modelisation plugin is not related to a vpz. This issue won't be fixed in vle 1.1 and is not relevant for the new gvle.
