### ISSUE TITLE
gvle: using too much a vpz make gvle very slow

### ISSUE THREAD

**Issue by GG31** [vle-forge/vle#180]
Using too much a vpz multiply <double>...</double> items. Then parsing the vpz take a very long time because the file have thousands of lines.

**Comment by rtrepos** [comment]
For the moment, the newer version of gvle (based on Qt) seems slower than the previous one. Especially, when opening a vpz with multiple simulations configurations. A solution will be in the future to externalize the experiment plan (rather than storing it into vpz conditions).
