### ISSUE TITLE
gvle: project's name

### ISSUE THREAD

**Issue by GG31** [vle-forge/vle#181]
if you call your project with points for example vle.extension.example every model M will be on the namespace vle.extension.example and will have DECLARE_DYNAMICS(vle.extension.example::M)
That doesn't compile.

**Comment by rtrepos** [comment]
A checking of names should be provided in gvle, especially when dealing with names that go into c++ files.

**Comment by rtrepos** [comment]
This is related to #240

**Comment by quesnel** [comment]
Closing now. Feel free to reopen. Thanks.

**Comment by quesnel** [comment]
Closing now. Feel free to reopen. Thanks.
