### ISSUE TITLE
utils/tools could have more operators of type comparison and conversion

### ISSUE THREAD

**Issue by Chabrier** [vle-forge/vle#182]
Could be very convenient to have a "local" argument for the "is" or "to" method, to be at the same level
than convert.

By the way surprisingly le convert from string to double never fail, and returns 0.0 if the conversion is not possible. For controlling a time step it is acceptable, but in most case it is a limitation.

**Comment by quesnel** [comment]
Seems to be fix, closing now. Feel free to reopen if you still see some warnings.
