### ISSUE TITLE
gvle2: which xml parser to use ?

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#197]
In gvle2 :
- in src/vle/gvle2/vleVpz.h : xml parser based on QT isued 
- in src/vle/gvle2/simulation.cpp (simulationView::setVpz) : le vle::vpz API is used to get views and then it is libxml

Should we keep both ? what are the rules for using either QT xml parser or libxml ?

**Comment by Chabrier** [comment]
good question...i'm going to have a look

**Comment by Chabrier** [comment]
Ok i understand your question...I think? 
do you mean, should we ban everywhere inside gvle2 a direct usage of the vle::vpz API?

Do you think this is possible?

**Comment by rtrepos** [comment]
Finally, 
QTXmlParser (DOM parser) is used for in gvle2 for GUI.
libxml2 (SAX parser) is used in vle for simulation, it allows to load heavy vpz that can not be opened in GUI.
