### ISSUE TITLE
output: storage crashes when all the sizes are set to 1

### ISSUE THREAD

**Issue by Chabrier** [vle-forge/vle#225]
When all the parameters of the storage plugin are set to 1, the simulation does crash.

example:
    <map>
       <key name="columns">
        <integer>1 </integer>
       </key>
       <key name="inc_columns">
        <integer>1 </integer>
       </key>
       <key name="inc_rows">
        <integer>1 </integer>
       </key>
       <key name="rows">
        <integer>1 </integer>
       </key>
      </map>

**Comment by quesnel** [comment]
Seems to be fix, closing now. Feel free to reopen if you still see some warnings.
