### ISSUE TITLE
NDEBUG option given by cmake

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#235]
Between cmake versions 2.8.9 and 2.8.10, CMake developpers have set NDEBUG flag in the RelWithDebInfo build type (commit  2010-08-20). The consequence is that the verbose mode 3 of vle does not print debug messages (especially bags for me) in this build type. 

I have tested and in Debug build type (cmake version 2.8.12.2), message are printed as expected. 

Do we now consider that the verbose mode of vle is provided only in Debug build type ?

**Comment by quesnel** [comment]
> Do we now consider that the verbose mode of vle is provided only in Debug build type ? 

Yes. For me it is not a problem at all.

**Comment by quesnel** [comment]
In fact, all verbose mode impacted (see Trace.hpp). If you use
DTraceAlways, DTraceModel, DTraceExtension or DTraceDevs macros, log are
removed with the CPPFLAGS -DNDEBUG. Other macros are ok. TraceAlways,
TraceModel, TraceExtension of TraceDevs
