### ISSUE TITLE
vle-1.1.2 and vle-1.1.3vle.conf not created

### ISSUE THREAD

**Issue by baratte** [vle-forge/vle#238]
Hi,

By installing vle on a dedicated and empty linux account (home/vle), it seems the vle configuration file is not created in /home/vle/.vle.
Consequently, when I install manually the packages, I have the following error

> vle@server:~/vle-1.1.3/packages[master1.1]> vle -P vle.extension.difference-equation configure build  test
> ---Preferences: vle.packages.configure is not a string
> ---Preferences: vle.packages.test is not a string
> ---Preferences: vle.packages.build is not a string
> ---Preferences: vle.packages.install is not a string
> ---Preferences: vle.packages.clean is not a string
> ---Preferences: vle.packages.package is not a string
> ---Preferences: vle.packages.unzip is not a string
> terminate called after throwing an instance of 'vle::utils::FileError'
>   what():  Pkg configure error: empty command
> Abandon

This error happens with both vle-1.1.2 and vle-1.1.3

**Comment by rtrepos** [comment]
Hello Christine,
This is definitely a bug. 
A way maybe to avoid it: use this command before trying to compile a pkg (one or two times):
vle --restart

**Comment by rtrepos** [comment]
fixed in vle2
