### ISSUE TITLE
improve vle cli 

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#254]
One should be allowed to call the simulation for any absolute path of vpz model.
eg: vle /tmp/mymodel.vpz

For the moment we have to specify a package
eg: vle -P mypkg /tmp/mymodel.vpz

Then: for spawned sub simulations, remove the package argument into signature of manager::Manager::run and manager::Simulation::run

**Comment by quesnel** [comment]
Fixed in 75e3a69d17837f8336fec92865a3ce4773e290cc
