### ISSUE TITLE
mvle: errors launching mpirun

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#262]
Launching mvle (on genotoul cluster), an error sometimes occurs using mpirun (exit status 1).
This error occurs ramdomly (I did not find a process to reproduce the bug,  ie, same expe leads to this error or not)

Looking at the log of execution, I get a warning considering the launch of mpirun.

*****************************************
An MPI process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your MPI job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.  

The process that invoked fork was:

  Local host:          node043 (PID 59497)
  MPI_COMM_WORLD rank: 11

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
*******************************************

It seems to me that the same experiments before applying  the patch  
8c6bec19f3cbf64a21f34c9fe1237c4f9295dbef (that introduces the spawn process in mvle)  did work.
Could it be related ?

**Comment by quesnel** [comment]
Closing now. Feel free to reopen. Thanks.
