### ISSUE TITLE
cvle: radnom SegFault when using Spawn

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#267]
Some simulations finish with a segfault on the genotool cluster (not on my computer) when using cvle.
Modifyiing cvle by not using the Spawn for simulations seems to work.

My experiment:

--------------------------------
mpirun --mca mpi_warn_on_fork 0 -np 2 cvle --package vle.discrete-time_test model1.vpz -i test_expe_cvle.txt -o out.csv
--------------------------------
On parallel_rr environment with 2 slots and with test_expe_cvle.txt:

--------------------------------
condC1.init_value_c
1
2
...
30
---------------------------------

The backtrace of the core dump:

(gdb) bt
#0  0x00007f2b0ae2e5d0 in ?? ()
#1  <signal handler called>
#2  opal_memory_ptmalloc2_int_malloc (av=0x7f2b1fb72740, bytes=160) at malloc.c:4018
#3  0x00007f2b1f93ddaf in opal_memory_ptmalloc2_int_memalign (av=0x7f2b1fb72740, alignment=32, bytes=<value optimized out>) at malloc.c:4876
#4  0x00007f2b1f93ea03 in opal_memory_ptmalloc2_memalign (alignment=32, bytes=78) at malloc.c:3642
#5  0x0000003724480e92 in strdup () from /lib64/libc.so.6
#6  0x00007f2b2081939d in vle::utils::Spawn::Pimpl::initchild(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >) () at /home/rtrepos/save/vledev/vle/src/vle/utils/details/SpawnUnix.cpp:104
#7  0x00007f2b208174f5 in vle::utils::Spawn::start(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::chrono::duration<long, std::ratio<1l, 1000l> >) () at /home/rtrepos/save/vledev/vle/src/vle/utils/details/SpawnUnix.cpp:324
#8  0x00007f2b208cf14e in vle::manager::Simulation::Pimpl::runSubProcess(std::unique_ptr<vle::vpz::Vpz, std::default_delete<vle::vpz::Vpz> >, vle::manager::Error*) ()
    at /home/rtrepos/save/vledev/vle/src/vle/manager/Simulation.cpp:271
#9  0x00007f2b208cea66 in vle::manager::Simulation::run(std::unique_ptr<vle::vpz::Vpz, std::default_delete<vle::vpz::Vpz> >, vle::manager::Error*) ()
    at /home/rtrepos/save/vledev/vle/src/vle/manager/Simulation.cpp:382
#10 0x000000000041816d in run_as_worker(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::chrono::duration<long, std::ratio<1l, 1000l> >, bool) () at /home/rtrepos/save/vledev/vle/src/apps/mvle/cvle.cpp:486
#11 0x000000000042354b in main () at /home/rtrepos/save/vledev/vle/src/apps/mvle/cvle.cpp:905

**Comment by quesnel** [comment]
Closing now. Feel free to reopen. Thanks.
