### ISSUE TITLE
c++14 and qt5

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#273]
It seems that linking targets (vlelib, gvlelib) to qt5 libraries forces cmake not to compile in c++14.
We get the issue described here:
http://stackoverflow.com/questions/40795474/qt-5-7-adding-std-gnu11-to-my-compiler-flags-clobbering-std-c14

**Comment by quesnel** [comment]
Seems to be fix, closing now. Feel free to reopen if you still see some warnings.
