### ISSUE TITLE
vle utils: FileError really required ?

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#277]
In PackageParser.cpp fction read_packages, a FileError is sent if the parsing of a Description file fails for an installed pkg. For the moment gvle aborts if one package Description file is mal formed. Should gvle handle this error or can we just remove the package with the mal formed Description file from vle::utils ?

**Comment by quesnel** [comment]
The `abort()` is due to noexcept. This is fix in #315. But mal formed description files are still not available in GVLE. We need to improve debug, info report in GVLE. See #316.
