### ISSUE TITLE
gvle: simplifying date management ?

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#278]
In record models, condition port simulation_engine.begin is now not used to index to a date (eg 1999-01-01). A new port is required (eg begin_date for the meteo file reader), simulation_engine.begin can be kept to 0, and conversion of dates to julian day number can be managed by the condition plugin date. Simulation dates can be observed on the meteo reader port 'current_date' and 'current_date_str'. Thus functionalities in gvle to manage dates can be removed:

- The 'Begin' and 'Begin Date Time'  boxes of the Project Panel of the VPZ editor.
- The "Convert date into julian day" option of vle.output/storage 
- (Also what about the 'Flush by bag' option of vle.output/storage ? is it still usefull ?)

Any objection ?

**Comment by rtrepos** [comment]
This will be removed

**Comment by quesnel** [comment]
Ok. No problem here.

**Comment by rtrepos** [comment]
Done
