### ISSUE TITLE
Simulation::runSubProcess improvments suggestions

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#287]
Simulation::runSubProcess use the Spawn utility to run the simulation. It is now the default behavior in rvle.
It produces a vpz temp file with conditions  and a vpz temp file with simulation results.
For now,
- one cannot parameterize the tmp directory where are produced the files (see make_temp)   
- tmp files are not removed once the simulation results are read.
Could it be parameterized ?

**Comment by quesnel** [comment]
You can set the tmp directory by overriding the TMPDIR environment
variable on POSIX or TMP on Windows.

For temporary files, we can add option to cleanup files.

**Comment by quesnel** [comment]
Closing now. Feel free to reopen. Thanks.
