### ISSUE TITLE
cvle memory leaks

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#289]
Using valgrind with cvle (33 simulations on 3 slots), we get this kinfd of errors:

==15363== 4 bytes in 1 blocks are still reachable in loss record 2 of 190
==15363==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15363==    by 0x9C56543: hwloc_bitmap_list_asprintf (in /usr/lib/x86_64-linux-gnu/libhwloc.so.5.6.8)
==15363==    by 0x7CAA9AC: orte_ess_base_proc_binding (in /usr/lib/openmpi/lib/libopen-rte.so.12.0.2)
==15363==    by 0xB4A05EC: ???
==15363==    by 0x7C87605: orte_init (in /usr/lib/openmpi/lib/libopen-rte.so.12.0.2)
==15363==    by 0x58DFA5E: ompi_mpi_init (in /usr/lib/openmpi/lib/libmpi.so.12.0.2)
==15363==    by 0x58FE54C: PMPI_Init (in /usr/lib/openmpi/lib/libmpi.so.12.0.2)
==15363==    by 0x5475DEA: boost::mpi::environment::environment(int&, char**&, bool) (in /usr/lib/x86_64-linux-gnu/libboost_mpi.so.1.58.0)
==15363==    by 0x4AFE64: main (cvle.cpp:1044)
==15363== 
==15363== 4 bytes in 1 blocks are definitely lost in loss record 3 of 190
==15363==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15363==    by 0x6D51489: strdup (strdup.c:42)
==15363==    by 0xBCAF655: ???
==15363==    by 0x7F3FCC6: opal_db_base_store (in /usr/lib/openmpi/lib/libopen-pal.so.13.0.2)
==15363==    by 0x7CAAA4C: orte_ess_base_proc_binding (in /usr/lib/openmpi/lib/libopen-rte.so.12.0.2)
==15363==    by 0xB4A05EC: ???
==15363==    by 0x7C87605: orte_init (in /usr/lib/openmpi/lib/libopen-rte.so.12.0.2)
==15363==    by 0x58DFA5E: ompi_mpi_init (in /usr/lib/openmpi/lib/libmpi.so.12.0.2)
==15363==    by 0x58FE54C: PMPI_Init (in /usr/lib/openmpi/lib/libmpi.so.12.0.2)
==15363==    by 0x5475DEA: boost::mpi::environment::environment(int&, char**&, bool) (in /usr/lib/x86_64-linux-gnu/libboost_mpi.so.1.58.0)
==15363==    by 0x4AFE64: main (cvle.cpp:1044)
==15363== 
==15363== 5 bytes in 1 blocks are still reachable in loss record 4 of 190
==15363==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15363==    by 0x4F0E861: xmlStrdup (in /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3)
==15363==    by 0x4E6C233: xmlNewCharEncodingHandler (in /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3)
==15363==    by 0x4E936C4: xmlInitParser (in /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3)
==15363==    by 0x4E718EA: xmlCheckVersion (in /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3)
==15363==    by 0xD8F5A8D: ???
==15363==    by 0x9C5B772: ??? (in /usr/lib/x86_64-linux-gnu/libhwloc.so.5.6.8)
==15363==    by 0x9C53130: ??? (in /usr/lib/x86_64-linux-gnu/libhwloc.so.5.6.8)
==15363==    by 0x9C4BB60: hwloc_topology_set_xmlbuffer (in /usr/lib/x86_64-linux-gnu/libhwloc.so.5.6.8)
==15363==    by 0x7F509B5: opal_hwloc_unpack (in /usr/lib/openmpi/lib/libopen-pal.so.13.0.2)
==15363==    by 0x7F161BE: opal_dss_unpack_buffer (in /usr/lib/openmpi/lib/libopen-pal.so.13.0.2)
==15363==    by 0x7F170DD: opal_dss_unpack (in /usr/lib/openmpi/lib/libopen-pal.so.13.0.2)

**Comment by quesnel** [comment]
Are all simulations succeeded (no failure)?

**Comment by rtrepos** [comment]
Yes there is no simulation error

**Comment by quesnel** [comment]
This is a boost.MPI or an openmpi memory leaks?

**Comment by quesnel** [comment]
Closing now. Feel free to reopen. Thanks.
