### ISSUE TITLE
vpz: bug in Views.cpp ?

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#290]
In Views::delObservable implementation, the list of views is cleared (vle/vpz/Views.cpp:83).
I think the will was to detach views from the observable, but here it seems that the View objects are removed.
I think they should not be removed.

**Comment by quesnel** [comment]
Yes. They shouldn't be removed.

But, is this function used? I see only a reference in PyVLE.

**Comment by rtrepos** [comment]
No indeed, but I planned to use it (but I can use something else)

**Comment by quesnel** [comment]
Ok. So, we have to fix it.
