### ISSUE TITLE
inconsistency in vpz::BaseModel::findModel implementations ?

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#292]
CoupledModel::findModel(const std::string& mod)  overrides this functions by searching 'mod' amongst the children of the coupled model represented by 'this'.

AtomicModel::findModel(cosnt std::string& mod) checks if 'this' model has name model.

In the first implementation we don't include the root model, in the other we do include it.

Iterating on sub model of a coupled model (that contains a coupled model 'mod', which also contains an atomic model 'mod'). Calling BaseModel::findModel ('mod') on the submodel isn't enough to determine if we have to deal with a coupled model or an atomic. Further checkings are required. 

My opinion is that we better should return nullptr in AtomicModel::findModel, whatever is the model name argument.

**Comment by quesnel** [comment]
> Iterating on sub model of a coupled model (that contains a coupled
> model 'mod', which also contains an atomic model 'mod'). Calling
> BaseModel::findModel ('mod') on the submodel isn't enough to
> determine if we have to deal with a coupled model or an
> atomic. Further checkings are required.

- CoupledModel::findModel() checks only direct children (no recursive).

- vpz::BaseModel, vpz::AtomicModel and vpz::CoupledModel must be seen
  as depreciated (and should be VLE_LOCAL instead of VLE_API).

**Comment by rtrepos** [comment]
And is there something that would replace it, or another process to iterate on children for example ?
findModelFromPath ?

**Comment by quesnel** [comment]
> And is there something that would replace it, or another process to
> iterate on children for example ?  findModelFromPath ?

Yes!

https://github.com/vle-forge/vle/blob/master/src/vle/vpz/BaseModel.hpp#L113
