### ISSUE TITLE
gvle: In order to keep the XML attributes order consistent inside the VPZ

### ISSUE THREAD

**Issue by Chabrier** [vle-forge/vle#294]
the solution consist in using a QT_HASH_SEED env variable, confer the following link
[https://stackoverflow.com/questions/21535707/qtxml-incorrect-order-of-attributes](https://stackoverflow.com/questions/21535707/qtxml-incorrect-order-of-attributes)

We could provide an optional parameter inside the gvle.conf file.

example:
qSetGlobalQHashSeed(42); // set a fixed hash value

**Comment by quesnel** [comment]
We have no need to keep attributes order. We use a for-ranger loop to parse XML attributes.
For example:
https://github.com/vle-forge/vle/blob/master/src/vle/vpz/SaxStackVpz.cpp#L151
