### ISSUE TITLE
gvle - windows: date in "Project" panel 

### ISSUE THREAD

**Issue by helraynal** [vle-forge/vle#329]
It isn't possible to change it.

**Comment by Chabrier** [comment]
Hi,

i could not reproduce the problem.

Could you tell the version of gvle, and the OS.

Thanks.

**Comment by helraynal** [comment]
Me too … But I think  I tried to choose a calendar date which was after the current day. The problem occurs only in this case, so it is not really a bug.


De : Patrick Chabrier <notifications@github.com>
Envoyé : jeudi 3 mai 2018 11:38
À : vle-forge/vle <vle@noreply.github.com>
Cc : Helene Raynal <helene.raynal@inra.fr>; Author <author@noreply.github.com>
Objet : Re: [vle-forge/vle] gvle - windows: date in "Project" panel (#329)


Hi,

i could not reproduce the problem.

Could you tell the version of gvle, and the OS.

Thanks.

**Comment by quesnel** [comment]
Closing now. Feel free to reopen. Thanks.
