### ISSUE TITLE
gvle-windows:   crash

### ISSUE THREAD

**Issue by helraynal** [vle-forge/vle#330]
a gvle crash often occurs  when adding a 2nd output port on an atomic model.

**Comment by Chabrier** [comment]
This does not seems to always occurs.
Could you tell which version and OS you are using.

And also do you have an idea on a favorable use case to reproduce the bug?

Thanks anyway.

**Comment by quesnel** [comment]
Seems to be fix, closing now. Feel free to reopen if you still see some warnings.
