### ISSUE TITLE
gvle : invalid vpz file not detected

### ISSUE THREAD

**Issue by eric-casellas** [vle-forge/vle#341]
If for example you have an empty text file, with .vpz file extension, in the exp folder of a package.
When opening this file from gvle, the simulator open and display an empty structure and no warning/error message in the log panel.

Note : one can also then edit and save the file, and the file remain unchanged (still empty)

**Comment by quesnel** [comment]
Do you want to fix this issue?

**Comment by eric-casellas** [comment]
not really as I don't have any clue on which part of the source code is involved in this behaviour...

**Comment by eric-casellas** [comment]
it seems fine to me, with my test vpz there was a notification popup as well as a message in the log panel
