### ISSUE TITLE
cvle: change in output format

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#346]
Since this commit : 
cvle: fixed csv format generation (2018-05-30), 

The output format of the cvle file (aggregating the results in one file) has a different format.

Especially we don't have access to the name of the view anymore :

-                    os << "view:" << it->first << "\n" << vle::value::toMatrixValue(it->second);
+                    it->second->writeFile(os);

This was used to identify outputs in the vle.recursive package.
Is it possible to reset the name of the view as a preamble of the data ? Or is there a reason why  it has been discarded ?

**Comment by quesnel** [comment]
With the following code, the file generated is not a csv format
(multiple new line character).

We can add a command line option (``--more-output-details``|``-m``) to
use old format if you want but default, we use ``it->second->writeFile(os)``.

**Comment by rtrepos** [comment]
Ok, I can work on a proposal for this option of cvle if you are ok.

But just for my understanding, I don't see how come the generated file with the default behavior has csv format, especially when there is more than 1 view. For example simulating   

vle -P vle.recursive_test build ExBohachevskyMM_cvle.vpz

gives this file:

id_0_0
time,ExBohachevsky:ExBohachevsky.y,ExBohachevsky:ExBohachevsky.y_noise
inf,2.096000000000000e+02,2.096427961723182e+02
time,ExBohachevsky:ExBohachevsky.y_noise
0.000000000000000e+00,2.096427961723182e+02
1.000000000000000e+00,2.096427961723182e+02
2.000000000000000e+00,2.096427961723182e+02
3.000000000000000e+00,2.096427961723182e+02
4.000000000000000e+00,2.096427961723182e+02
5.000000000000000e+00,2.096427961723182e+02
6.000000000000000e+00,2.096427961723182e+02
7.000000000000000e+00,2.096427961723182e+02
8.000000000000000e+00,2.096427961723182e+02
9.000000000000000e+00,2.096427961723182e+02
1.000000000000000e+01,2.096427961723182e+02

id_0_1
time,ExBohachevsky:ExBohachevsky.y,ExBohachevsky:ExBohachevsky.y_noise
inf,2.096000000000000e+02,2.094757619176503e+02
time,ExBohachevsky:ExBohachevsky.y_noise
0.000000000000000e+00,2.094757619176503e+02
1.000000000000000e+00,2.094757619176503e+02
2.000000000000000e+00,2.094757619176503e+02
3.000000000000000e+00,2.094757619176503e+02
4.000000000000000e+00,2.094757619176503e+02
5.000000000000000e+00,2.094757619176503e+02
6.000000000000000e+00,2.094757619176503e+02
7.000000000000000e+00,2.094757619176503e+02
8.000000000000000e+00,2.094757619176503e+02
9.000000000000000e+00,2.094757619176503e+02
1.000000000000000e+01,2.094757619176503e+02

...

**Comment by quesnel** [comment]
On mer. 04 juil. 18, rtrepos wrote:
> Ok, I can work on a proposal for this option of cvle if you are ok.

Yes. I am ok!

> But just for my understanding, I don't see how come the generated file
> with the default behavior has csv format, especially when there is
> more than 1 view. For example simulating   
> 
> vle -P vle.recursive_test build ExBohachevskyMM_cvle.vpz
> gives this file:
> 
> id_0_0
> time,ExBohachevsky:ExBohachevsky.y,ExBohachevsky:ExBohachevsky.y_noise
> inf,2.096000000000000e+02,2.096427961723182e+02
> time,ExBohachevsky:ExBohachevsky.y_noise
> 0.000000000000000e+00,2.096427961723182e+02
> 1.000000000000000e+00,2.096427961723182e+02
> 2.000000000000000e+00,2.096427961723182e+02
> 3.000000000000000e+00,2.096427961723182e+02
> 4.000000000000000e+00,2.096427961723182e+02
> 5.000000000000000e+00,2.096427961723182e+02
> 6.000000000000000e+00,2.096427961723182e+02
> 7.000000000000000e+00,2.096427961723182e+02
> 8.000000000000000e+00,2.096427961723182e+02
> 9.000000000000000e+00,2.096427961723182e+02
> 1.000000000000000e+01,2.096427961723182e+02
> 
> id_0_1
> time,ExBohachevsky:ExBohachevsky.y,ExBohachevsky:ExBohachevsky.y_noise
> inf,2.096000000000000e+02,2.094757619176503e+02
> time,ExBohachevsky:ExBohachevsky.y_noise
> 0.000000000000000e+00,2.094757619176503e+02
> 1.000000000000000e+00,2.094757619176503e+02
> 2.000000000000000e+00,2.094757619176503e+02
> 3.000000000000000e+00,2.094757619176503e+02
> 4.000000000000000e+00,2.094757619176503e+02
> 5.000000000000000e+00,2.094757619176503e+02
> 6.000000000000000e+00,2.094757619176503e+02
> 7.000000000000000e+00,2.094757619176503e+02
> 8.000000000000000e+00,2.094757619176503e+02
> 9.000000000000000e+00,2.094757619176503e+02
> 1.000000000000000e+01,2.094757619176503e+02

At the beginning, cvle only run with a "finish" view (no "timed" or
"event"). So, views can be concatenated without any break-line or
new-line.

Perhaps a new output file format can be produce instead of csv. A json
or yaml is better for this king of output.

**Comment by rtrepos** [comment]
Actually there is another issue with this format, the comma is already used to separate coupled model to submodels in the format of the observed port eg. :

coupled1,coupled2:atomic.port 

CSV will interpret this like 2 columns while this is actually only one.

**Comment by rtrepos** [comment]
Hi, is there any starting idea on how we could use json or yaml for this output ? What should this format look like ? What are the specifications we should follow in order to benefit from using these formats ? What are the advantages ? I am ok to take a look at it but do not know much about it.
