### ISSUE TITLE
About std::ostream* os parameter of RemoteManager::start

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#348]
Is this really usefull to provide this function signature. The os parameter is used to write information messages but there is already a Context embedded into the RemoteManager that can be used to log messages. Beside, the errors are written with the context from the RemoteManager constructor.

One could remove the os parameter and rely on context->log_fn functor to write information messages.

**Comment by quesnel** [comment]
Yes. We can delete this useless parameter and move error code to the
context functor.

Be careful however. We need to limit API break between VLE 2.0 and 2.1
to restrict package changes.

**Comment by rtrepos** [comment]
Done in commit 3011028ddcf429261588946bd5b4d65c77b2c753
