### ISSUE TITLE
setting utils::Context log_priority field

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#349]
If vle is compiled without VLE_DISABLE_DEBUG macro (which is the default case because of the cmake variable WITH_DEBUG default value set to ON) the utils::make_context() will by default set log_priority to 7 and print a message. This message starts with  'Context initialized...'

If one wants to avoid the message to be printed each time the make_context is called, the VLE_DISABLE_DEBUG has to be set (by forcing WITH_DEBUG = OFF) but, then, the utils::debug function are not usefull anymore, even if one speciffically calls set_log_priority(7) 

There is no way to avoid the message to be printed without lossing the other debug messages.
For example launching a simple vpz with verbose 0 will print this message and only this message which is not the most important.

Suggestions to change this behavior :
- add the log_priority as an argument of make_context
- or do not print this message (even in the debug mode)

**Comment by quesnel** [comment]
I agree. It's a problem. I propose to remove this message just.
