### ISSUE TITLE
bug in Context::log functions ?

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#350]
the log functions do not take into account the priority parameter.
It will print the message whatever the priority is.

Is there a missing condition such as :

if (m_pimpl->log_priority >= priority)

**Comment by quesnel** [comment]
On Wed 10 Oct 18, rtrepos wrote:
> the log functions do not take into account the priority parameter.
> It will print the message whatever the priority is.
> 
> Is there a missing condition such as :
> if (m_pimpl->log_priority >= priority)

Yes, you are right.
