### ISSUE TITLE
remote install from windows - still pb occurs

### ISSUE THREAD

**Issue by helraynal** [vle-forge/vle#360]
An error occurs when using the remote install from gvle (2.0.2) on Windows (Win10). (
The tar.bz2 dowmloaded before extraction is only 1ko (instead of 30ko).

**Comment by helraynal** [comment]
As it didn't work this morning,  I installed the most mandatory vle packages "by hand". 
Now, I've just tried  to   install other vle packages , after removing the vle.conf. It seems OK, but I am not sure if I've installed packages from 2.0 distribution  or from 2.1 .
I ve the same problem when I try to install record packages.

**Comment by quesnel** [comment]
Ok. As packages from VLE 2.1 and 2.0 are the same, I think the URLs in `vle.conf` was not good.

If the removing of `vle.conf` fix the problem, perhaps we can add an option menu in GVLE to remove/replace the configuration files. @Chabrier what do you think?

**Comment by Chabrier** [comment]
A kind of "reset the default config file" bouton with a backup, or not?
Or with a "are you confident?" "are you very confiedent??" question  :):):)

Why not.

**Comment by quesnel** [comment]
:)
Yes a `reset the default config files` in the help menu for examples will help windows user.

**Comment by Chabrier** [comment]
43b5db508f24953139cbd533a1fd3b6e3f70cc50 does provide a proposition of feature

**Comment by quesnel** [comment]
Thank you. Patch available in next VLE versions 2.1 and 2.0.3.
