### ISSUE TITLE
rvle - windows

### ISSUE THREAD

**Issue by helraynal** [vle-forge/vle#361]
Message when running the following lines:
library("rvle")
f = new("Rvle", file = "2CV-exploration.vpz", pkg = "2CV");

"failed to initialized prefix from registry . Try to use the current executable to determine the prefix but access to cmake , curl or wge will fail"

**Comment by helraynal** [comment]
Eric has suggested that it was a pb of R version (too old). I confirm I have installed R version 3.5.1 and it seems fine now.

**Comment by quesnel** [comment]
Ok. I add two commits to the VLE website about the minimal R version to use RVLE:
- https://github.com/quesnel/vle-project.org/commit/20bedb46f63dfa7ab07af42c1c275fc683e9a7e2
- https://github.com/quesnel/vle-project.org/commit/63f9432767b599cdd431be385e6a1fdf93a0e86a

**Comment by quesnel** [comment]
I close this issue.
