### ISSUE TITLE
gvle: undefine symbols from QCustomPlot

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#372]
On master branch.
When using the plot of gvle, an error occurs which is related to the missing link with QCustomPlot.
The cmake macro DeclareGvle does not link the target with QCustomPlot (QCustomPlot_LIBRARIES).
The solution depends on the strategy :
- should qcustomplot be available for all the UI, which makes it a dependency of gvle.
- or only for DefaultSimsubpanel

**Comment by quesnel** [comment]
Link only with the DefaultSimsubpanel.

**Comment by quesnel** [comment]
Can you test this patch @rtrepos ?

**Comment by rtrepos** [comment]
Hi, Not sure yet it is working.
I tried to modify the template dynamics (Simple.cpp) in order to observe a value::Double and I had another error : 

symbol lookup error: /pub/vlehomeexp/vle-2001/pkgs/titi/plugins/simulator/libSimple.so: undefined symbol: _ZN3vle7versionEv

Not related bu prevent me from testing the commit.
I will dig further.

**Comment by rtrepos** [comment]
It is ok you can push this commit on master.
Thanks.

**Comment by quesnel** [comment]
0k. Merged. Thx.
