### ISSUE TITLE
Win32 installer:  pkg config is not available 

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#376]
The Win32 installation process given in the doc repositoriy does not provide a pkg-config wich is usefull for finding EXPAT through CMake

NB: I use new versions of vle dependencies
msys2-i686-20180531.exe
qt-unified-windows-x86-3.1.0
cmake-3.14.3-win32
boost 1.70
innosetup 6.0.2

**Comment by quesnel** [comment]
In https://github.com/quesnel/vle/blob/master/appveyor.yml#L80 pkg-config from msys2 is not used (PATH does not include any msys2 bin). pkg-config is not installed with qt-creator?

**Comment by rtrepos** [comment]
No I don't think so.
There is the pacman package for pkg-config.exe but it requires to set the msys2 bin directory into the path.

**Comment by quesnel** [comment]
You try to build VLE 2.0 or VLE 2.1?

**Comment by quesnel** [comment]
> I try to build the master branch 

Ok. I don't try to build Master branch. The documentation is for Master 2.0.x. With the 2.0.x we don't rely on pkg-config.

**Comment by rtrepos** [comment]
Ok, actually pkg-config is used by FindEXPAT to find the expat lib.

**Comment by quesnel** [comment]
On Thu 16 May 19, rtrepos wrote:
> Ok, actually pkg-config is used by FindEXPAT to find the expat lib.

Yes. The documentation is bad.

I think adding a cmake variable (CMAKE_PREFIX_PATH?) to the cmake command line will help the find_path and find_library functions to found the libexpat.

https://cmake.org/cmake/help/latest/command/find_path.html

**Comment by rtrepos** [comment]
Ok thanks.
I finally used the pkg-config executable from Mingw and set PKG_CONFIG_PATH.
Now, I have difficulties to compile QCustomPlot which is no longer available in vle.
