### ISSUE TITLE
vle::utils::Package : error in the path of binary package

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/vle#380]
vle.generic.builder is a system package and is not installed in VLE_HOME.
Yet, using the command : `vle -P vle.generic.builder list`

we get the following message 

```
Package content from: /pub/vlehomeexp/vle-2001/pkgs/vle.generic.builder
-- simulator plugins:
-- output plugins:
-- gvle output plugins:
-- gvle condition plugins:
-- gvle simulating plugins:
-- gvle modeling plugins:
-- gvle out plugins:
-- gvle vpz plugins:
-- gvle data plugins:
```

The binary is thought to be in VLE_HOME whereas it is in the install directory of vle. The simulator is not found.
And the expected message is :

```
Package content from: /pub/install/vleexp/lib/vle-2.1/pkgs/vle.generic.builder
-- simulator plugins:
/pub/install/vleexp/lib/vle-2.1/pkgs/vle.generic.builder/plugins/simulator/libBuilder.so
-- output plugins:
-- gvle output plugins:
-- gvle condition plugins:
-- gvle simulating plugins:
-- gvle modeling plugins:
-- gvle out plugins:
-- gvle vpz plugins:
-- gvle data plugins:

```

**Comment by rtrepos** [comment]
There are 8 different situations depending on 
- the source package exists (in the current path) noted SRC=1
- the user package exists (in VLE_HOME) noted USER=1
- the system package exists (in the install directory of VLE) noted SYS=1

One cannot know if the user wants to manage the package (eg. vle -P toto build) or to use the installed version (eg. vle -P toto toto.vpz). without deeply modifying the API.

I suggest one should set the  values of 'm_pkgbinarypath' and  'm_pkgsourcepath' in Package::refreshPath accoding the following rules :

SRC=0, USER=0, SYS=0   => m_pkgsourcepath=null   and m_pkgbinarypath=USER [1]
SRC=0, USER=0, SYS=1   => m_pkgsourcepath=null   and m_pkgbinarypath=SYS
SRC=0, USER=1, SYS=0   => m_pkgsourcepath=null   and m_pkgbinarypath=USER 
SRC=0, USER=1, SYS=1   => m_pkgsourcepath=null   and m_pkgbinarypath=USER [2]
SRC=1, USER=0, SYS=0   => m_pkgsourcepath=SRC and m_pkgbinarypath=USER [3] 
SRC=1, USER=0, SYS=1   => m_pkgsourcepath=SRC and m_pkgbinarypath=USER [4]
SRC=1, USER=1, SYS=0   => m_pkgsourcepath=SRC and m_pkgbinarypath=USER  
SRC=1, USER=1, SYS=1   => m_pkgsourcepath=SRC and m_pkgbinarypath=USER

[1]  in order to keep the old functionning, 
[2] the user can use its own package already installed in VLE_HOME (eg. testing an update of a system package)
[3] the binary pkg is set to the USER path in order to install (old functionning)
[4] the binary pkg is set to the USER path in order to install but he cannot use the SYS package (this would require to modify the api in order to provide information on the action he wants to perform, whereas for the moment the package is built without knowing the action to perform)

To conclude, the USER binary pkg is always preferred to the SYS package; even when it is does not exist but the SRC and SYS pkgs exist (we make the assumption that he will build a new version of the SYS pkg)

**Comment by quesnel** [comment]
On Thu 08 Aug 19, rtrepos wrote:
> vle.generic.builder is a system package and is not installed in VLE_HOME.
> Yet, using the command : `vle -P vle.generic.builder list`
> we get the following message 

The user does not have to compile system package. Never. This is the
initial goal.
