### ISSUE TITLE
GVLE Segmentation Fault

### ISSUE THREAD

**Issue by duboz** [vle-forge/vle#382]
Right after opening a new project, GVLE seg-fault when selecting the empty.vpz file with a double click in the file panel of GVLE.

Error no SimPanelPlugin  "Default"
Thread 1 "gvle" received signal SIGSEGV, Segmentation fault.
0x00007fffe35c6e07 in vle::gvle::FileVpzSim::setVpz(vle::gvle::vleVpz*) () from $HOME/.vle/lib/vle-2.1/pkgs/gvle.default/plugins/gvle/vpz/libDefaultVpzPanel.so

**Comment by quesnel** [comment]
I can't reproduce this error.

Can you try to remove previous installation of VLE 2.0 and 2.1?

**Comment by duboz** [comment]
I supress cmake cache, reconfigure, get the info that QCustomplot package was missing, install it and recompile and it works now.

**Comment by quesnel** [comment]
No problem. Thank you!
