### ISSUE TITLE
manager: index overflow in accu_mono

### ISSUE THREAD

**Issue by quesnel** [vle-forge/vle#387]
@rtrepos  In `quantileOnSortedVect` function, an index overflow occurred at line 517: `quantile = (1-g)*x[j-1]  + g*x[j];` in the `manager/details/accu_mono.cpp` with the libstdc++ preprocessor option `-D_GLIBCXX_ASSERTIONS`.

The vector `x` have a size of 1 double.

If I protect the vector (`if (j == 1) quantile = (1-g) * x[j-1]; else ...`), I get the following error:

`../tests/manager/test_accumulators.cpp(60): test 'acc.quantile(0.25) != 2.95 (epsilon: 10e-4)`

**Comment by rtrepos** [comment]
Hello,
Ok I will have a look to it.
How can i set easily the -D_GLIBCXX_ASSERTIONS in vle cmake ? 
when does it occur ? every time ?  whe nthe size of the vector is 1 ?
Thanks.

**Comment by rtrepos** [comment]
If the length of the vector is one, we can return the value of the vector whatever is the qualite specified.
