### ISSUE TITLE
cmake specific target to generate pkg doxygen doc

### ISSUE THREAD

**Issue by eric-casellas** [vle-forge/vle#61]
May be it would better fit the usual workflow to have a separate specific cmake target to generate the pkg doxygen doc. This would allow not to generate doc when using target ALL but only using a new specific cmake target. 
(This would correspond to a workflow on development pkg, where you want to generate the doc only at the "end" when ready to release, without having to change the vle.conf file)

**Comment by quesnel** [comment]
@rtrepos feasible in default `vle/share/template/CMakeLists.txt` ?

**Comment by quesnel** [comment]
Closing now. Feel free to submit a PR. Thanks.
