### ISSUE TITLE
vle  : VleCheckAndDeclareGeneratedModelsConfig handling dynamics models

### ISSUE THREAD

**Issue by eric-casellas** [vle-forge/vle#74]
The current version of cmake/VleCheckAndDeclareGeneratedModelsConfig.cmake file provided in the template pkg, does not handle models that use Dynamics rather than an extension. It would be practical if it did, so that the user don't have to edit his src/CMakeLists.txt file even for devs models.

**Comment by rtrepos** [comment]
This part is improved in vle-dev, the declaration of dynamics is directly performed in cpp files.
